# Laura_Alejandra_Moreno_Rodriguez_Exercise_1



## **Introduction** Total 7

### 1. Say "Hello, World!" With Python

In [12]:
#Say "Hello, World!" With Python _LAMR
if __name__ == '__main__':
    print("Hello, World!")

Hello, World!


### 2. Python If-Else

In [18]:
# Python If-Else _LAMR
import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input().strip())
    if n % 2==1: 
        print("Weird") #n is odd
    else:  #n is not odd. It's even.
        if 2<= n <=5:
            print("Not Weird")
        elif 6<= n <=20:
            print("Weird")
        else:
            print("Not Weird")

 38


Not Weird


### 3. Arithmetic Operators

In [9]:
#Arithmetic Operators _LAMR
a = int(input())
    b = int(input())
    print(a+b) #addition
    print(a-b)  #diference
    print(a*b)  #product


 2
 3


5
-1
6


### 4. Python: Division

In [21]:
#Python: Division_lAMR
a = int(input())
b = int(input())
print(a//b) #integer division
print(a/b) #float division

 3
 5


0
0.6


### 5. Loops

In [36]:
#Loops_LAMR
n = int(input())
for i in range(n):
    print((i**2)) 


 5


0
1
4
9
16


### 6. Write a function: leap year

In [50]:
#Write a function_LAMR
#Leaf year
def is_leap(year):
    leap = False
    
    # Write your logic here
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 ==0:
                leap = True
            else:
                leap =False
        else:
            leap = True
    else:
        leap =False
    
    return leap

year = int(input())
print(is_leap(year))

 2000


True


### 7. Print function

In [61]:
#Print Function_LAMR
def print_numbers_as_string(n):
    result = ''  
    for i in range(1, n + 1):  
        result += str(i)  
    print(result)  

# Read input 
n = int(input())
print_numbers_as_string(n)

 5


12345


## **Basic Data Types** Total 6


### 1. List Comprehension

In [7]:
#List Comprehensions_LAMR
x = int(input())
y = int(input())
z = int(input())
n = int(input())
coordinates = [[i, j, k] for i in range(x + 1)
               for j in range(y + 1) 
               for k in range(z + 1) 
               if i + j + k != n]


print(coordinates)

 1
 1
 2
 3


[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 2]]


### 2. Find the Runner-Up Score!

In [3]:
#Find the Runner-Up Score!_LAMR
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())

    run = list(dict.fromkeys(arr))  #function
    run.sort()
    print(run[-2])

 5
 2 3 6 6 5


5


### 3. Nested Lists

In [13]:
#Nested Lists_LAMR
if __name__ == '__main__':
    num_students = int(input())
    students_scores = []

    for _ in range(num_students):
        name = input()
        score = float(input())
        students_scores.append([name, score])

    unique_scores = sorted(set(score for _, score in students_scores))

    if len(unique_scores) > 1:
        second_lowest_score = unique_scores[1]
        second_lowest_students = sorted(name for name, score in students_scores if score == second_lowest_score)

        for name in second_lowest_students:
            print(name)
    else:
        print("Missing scores to determine second lowest.")


 5
 Harry
 37.21
 Berry
 37.21
 Tina
 27.2
 Akriti
 41
 Harsh
 39


Berry
Harry


### 4. Finding the percentaje

In [21]:
#Finding the percentaje_LAMR

if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    
    print("%.2f" % (sum(student_marks[query_name]) / len(student_marks[query_name])))

 2
 Harsh 25 26.5 28
 Anurag 26 28 30
 Harsh


26.50


### 5. Lists

In [1]:
#Lists_LAMR
if __name__ == '__main__':
    N = int(input())
    
    
    list_commands = {
        "insert": lambda i, e: l.insert(i, e),
        "print": lambda: print(l),
        "remove": lambda e: l.remove(e),
        "append": lambda e: l.append(e),
        "sort": lambda: l.sort(),
        "pop": lambda: l.pop(),
        "reverse": lambda: l.reverse()
    }

    l = []
    
    for _ in range(N):
        command, *args = input().split()
        if command in list_commands:
            list_commands[command](*map(int, args))

 12
 insert 0 5
 insert 1 10
 insert 0 6
 print


[6, 5, 10]


 remove 6
 append 9
 append 1
 sort
 print


[1, 5, 9, 10]


 pop
 reverse
 print


[9, 5, 1]


### 6. Tuples

In [31]:
#Tuples_LAMR
if __name__ == '__main__':
    n = int(input())
    integer_list = tuple(map(int, input().split()))
    print(hash(integer_list))


 2
 1 2


-3550055125485641917


 ## **Strings** Total 14

### 1. sWAP cASE

In [70]:
#sawp case_LAMR

def swap_case(s):
    
    convert=''.join([s[i].lower() if s[i].isupper() else s[i].upper()  
    for i in range(len(str(s)))])
    return convert    
  


### 2. String Split and Join

In [72]:
#String split and join_LAMR

def split_and_join(line):
    # write your code here
    line = line.split(" ")
    line = "-".join(line)
    return(line)

    

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)


 this is a string


this-is-a-string


### 3. What's Your Name?

In [74]:
#What's Your Name?_LAMR
# Complete the 'print_full_name' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last
#

def print_full_name(first, last):
    # Write your code here
    print(f"Hello {first} {last}! You just delved into python.")



### 4. Mutations

In [76]:
#mutations_LAMR

def mutate_string(string, position, character):
    
    mutate = list(string)
    mutate[position] = character
    return "".join(mutate)
    

### 5. Find a string

In [78]:
def count_substring(string, sub_string):
    counting = 0
    for i in range(len(string)):
        if string[i:i + len(sub_string)] == sub_string:
            counting = counting +1
    return counting



### 6.String Validators

In [80]:
#validator_LAMR

if __name__ == '__main__':
    s = input()
    check_boolean = [False, False, False, False, False]
    
    for i in s:
        if i.isalnum():
            check_boolean[0] = True
        if i.isalpha():
            check_boolean[1] = True
        if i.isdigit():
            check_boolean[2] = True
        if i.islower():
            check_boolean[3] = True
        if i.isupper():
            check_boolean[4] = True    
        
    for x in check_boolean:
        print(x)



 qA2


True
True
True
True
True


### 7. Text Alignment

In [82]:
#Text Alignment_LAMR

thic_value = int(input())
for i in range(thic_value):
    string = 'H'*(i*2+1)
    print(string.center(thic_value*2, ' '))

for i in range(thic_value + 1):
    string = 'H'*thic_value + '   '*thic_value + 'H'*thic_value
    print(string.center(thic_value*6, ' '))
    

for i in range(int((thic_value + 1)/2)):
    string = 'H'*thic_value*5      
    print(string.center(thic_value*6, ' '))
    
for i in range(thic_value + 1):
    string = 'H'*thic_value + '   '*thic_value + 'H'*thic_value
    print(string.center(thic_value*6, ' '))
    
for i in range(thic_value):
    string = 'H'*((thic_value - i - 1)*2 + 1)
    print(' '*thic_value*4 + string.center(thic_value*2, ' '))


 5


    H     
   HHH    
  HHHHH   
 HHHHHHH  
HHHHHHHHH 
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
  HHHHH               HHHHH   
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


### 8. Text Wrap

In [84]:


def wrap(string, max_width):
    i= 1
    new_str = []
    for str in string:
        new_str.append(str)
        if i % max_width == 0:
            new_str.append('\n')
        i +=1
    return ''.join(new_str)
    
    
    return



### 9. Designer Door Mat

In [87]:
## Enter your code here. Read input from STDIN. Print output to STDOUT
n,m=map(int,input().split())

i=0
for i in range(n):
    if i<((n-1)/2):
        print((("."+"|"+".")*(2*i+1)).center(m,"-"))
    
    elif i==((n-1)/2):
        print("WELCOME".center(m,"-"))
        
    else:
        print((("."+"|"+".")*(2*((n-1)-i)+1)).center(m,"-"))


 7 21


---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


### 10. String Formatting

In [89]:
def print_formatted(number):
    width=len(bin(number))-2
    for i in range(1, number+1):
        print(f'{i:{width}} {i:{width}o} {i:{width}X} {i:{width}b}')



### 11.Alphabet Rango

In [91]:
def make_line(number_of_letters, size):
    x = 97 + size - number_of_letters
    line = ""
    for i in range(number_of_letters -1, -1, -1):
        line += chr(x+i) + "-"
    for i in range(1, number_of_letters):
        line += chr(x+i) + "-"
    return line[:-1]

def print_rangoli(size):
    m= ((size*2)-1) + (size-1) * 2
    for i in range(1, size+1):
        pattern = make_line(i, size)
        print(pattern.center(m, "-"))
    for j in range(size -1, 0, -1):
        pattern2 = make_line(j, size)
        print(pattern2.center(m, "-"))
        


### 12. Capitalize!

In [93]:

# Complete the solve function below.
def solve(s):
    s = s.split(' ')
    for i in range(len(s)):
        s[i] = s[i].capitalize()
    return ' '.join(s)
    


### 13. The Minion Game

In [95]:
def minion_game(string):
   
    vowels = 'AEIOU'
    kevin_score = 0
    stuart_score = 0
    
    n = len(string)
    for i in range(n):
        if string[i] in vowels:
            kevin_score += n - i  # All possible substrings starting from index i
        else:
            stuart_score += n - i  # All possible substrings starting from index i
    
    if kevin_score > stuart_score:
        print(f"Kevin {kevin_score}")
    elif stuart_score > kevin_score:
        print(f"Stuart {stuart_score}")
    else:
        print("Draw")




### 14. Merge the Tools!

In [97]:
import textwrap

def merge_the_tools(string, k):
    
    list1 = textwrap.wrap(string, k)
    
    for value in list1:
        str1 = ""
        for i in value:
            if i not in str1:
                str1 += i
        print(str1)  




 ## **Sets** Total 13

### 1. Introduction to sets

In [115]:
def average(array):
    n_values = set(array)
    return(sum(n_values)/len(n_values))
    

### 2. No idea!

In [117]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n, m = map(int, input().split())
elements = list(map(int, input().split()))
a = set(map(int, input().split()[:n]))
b = set(map(int, input().split()[:m]))
happiness = 0

for item in elements:  # Corrected variable name from 'itiem' to 'item'
    if item in a:
        happiness += 1
    elif item in b:
        happiness -= 1

print(happiness)  # Added print statement to output the result


 3 2
 1 5 3
 3 1
 5 7


1


### 3. Symetric Difference

In [119]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

m = int(input())
a = set(map(int, input().split()[:m]))
n = int(input())
b = set(map(int, input().split()[:n]))
result = a ^ b
for item in sorted(result):
    print(item)


 4
 2 4 5 9
 4
 2 4 11 12


5
9
11
12


### 4. Set.add()

In [121]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())
countries = set()
[countries.add(input()) for i in range(n)]
print(len(countries))


 7
 UK
 China
 USA
 France
 New Zealand
 UK
 France


5


### 5. Set .discard()  .remove() & .pop()

In [123]:
n = int(input())
s = set(map(int, input().split()))


for _ in range(int(input())):
    try:
        function, *key = input().split()
        mykey = [int(k) for k in key]
        getattr(s, function)(*mykey)
    except KeyError:
        pass
print(sum(s))


 9
 1 2 3 4 5 6 7 8 9
 10
 pop
 remove 9
 discard 9
 discard 8
 remove 7
 pop
 discard 6
 remove 5
 pop
 discard 5


4


### 6. Set .union() Operation

In [125]:
# Enter your code here. Read input from STDIN. Print output to STDOU

n_english = int(input())
roll_english = set(input().split())
n_french = int(input())
roll_french = set(input().split())


print (len(roll_english.union(roll_french)))


 9
 1 2 3 4 5 6 7 8 9 
 9
 10 1 2 3 11 21 55 6 8


13


### 7. Set .intersection() Operation

In [127]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n_english = int(input())
roll_english = set(input().split())
n_french = int(input())
roll_french = set(input().split())


print (len(roll_english.intersection(roll_french)))


 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


5


### 8. Set .difference() Operation

In [129]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n_english = int(input())
roll_english = set(input().split())
n_french = int(input())
roll_french = set(input().split())


print (len(roll_english.difference(roll_french)))


 9
  1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


4


### 9. Set .symmmetric_difference() Operation

In [131]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n_english = int(input())
roll_english = set(input().split())
n_french = int(input())
roll_french = set(input().split())


print (len(roll_english.symmetric_difference(roll_french)))


 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


8


### 10. Set Mutations

In [133]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())
A = set(map(int, input().split()))
N = int(input())

for i in range(N):
    command = input().split()
    B = set(map(int, input().split()))
    if command[0] == "intersection_update":
        A.intersection_update(B)
    if command[0] == "update":
        A.update(B)
    if command[0] == "symmetric_difference_update":
        A.symmetric_difference_update(B)
    if command[0] == "difference_update":
        A.difference_update(B)

print(sum(A))


 16
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
 4
 intersection_update 10
 2 3 5 6 8 9 1 4 7 11
 update 2
 55 66
 symmetric_difference_update 5
 22 7 35 62 58
 difference_update 7
 11 22 35 55 58 62 66


38


### 11. The Capitain's room

In [135]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

K = int(input()) #group members
number_list = list(map(int,input().split()))
conver_set = set(number_list)

for i in conver_set:
    number_list.remove(i)
    if i not in number_list:
        print(i)
    


 5
 1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 


8


### 12. Check subset

In [137]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

T = int(input())

for i in range(T):
    inp1, A = input(), set(input().split())
    inp2, B = input(), set(input().split())
        
    print(A.issubset(B))


 3
 5
 1 2 3 5 6
 9
 9 8 5 6 3 2 1 4 7


True


 1
 2
 5
 3 6 5 4 1


False


 7
 1 2 3 5 6 8 9
 3
 9 8 2


False


### 13. Check strict superset

In [143]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

A_set=set(map(int, input().split()))
is_superset = True
for i in range(int(input())):
    if not A_set.issuperset(set(map(int, input().split()))):
        is_superset = False
        break
print(is_superset)



 1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
 2
 1 2 3 4 5
 100 11 12


False


 ## **Collections** Total 8

### 1. collections.counter()

In [5]:
from collections import Counter

nun_shoes = int(input())
shoe_sizes = Counter(map(int, input().split()))
N = int(input())
total = 0

for i in range(N):
    size, price = map(int, input().split())
    if shoe_sizes.get(size, 0) > 0:
        shoe_sizes[size] -= 1
        total += price
        if shoe_sizes[size] == 0:
            del shoe_sizes[size]
print(total)

 10
 2 3 4 5
 6
 5 20
 3 10
 1 15
 5 20
 4 100
 2 200


330


### 2. DefaultDic Tutorial

In [199]:
# Enter your code here. Read input from STDIN. Print output to STDOU

from collections import defaultdict

I = defaultdict(list)

a, b = map(int, input().split())
A = [str(input()) for _ in range(a)]
B = [str(input()) for _ in range(b)]

   
E = list(enumerate(A))

for _ in E:
    I[_[1]].append(_[0]+1)
    
for b in B:
    if b in A:
        print(*I[b])
    else:
        print(-1)

 5 2
 a
 a
 b
 a
 b
 a
 b


1 2 4
3 5


### 3. collections.namedtuple()

In [201]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from collections import namedtuple
num_students = int(input())
w, x, y, z = input().split()
Student = namedtuple('Student', f'{w} {x} {y} {z}')
total = 0

for i in range(num_students):
    w2, x2, y2, z2 = input().split()
    student = Student(w2, x2, y2, z2)
    total += int(student.MARKS)
print(total / num_students)


 5
 ID MARKS NAME CLASS
 1          97         Raymond    7
 2          50         Steven     4
 3          91         Adrian     9
 4          72         Stewart    5
 5          80         Peter      6


78.0


### 4. collections.OrderedDic()

In [203]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from collections import OrderedDict

num = int(input())
item_dict = OrderedDict()


for i in range(num):
    item_name, net_price = input().rsplit(maxsplit=1)
    net_price = int(net_price)
    item_dict[item_name] = item_dict.get(item_name, 0) + net_price


[print(item, price) for item, price in item_dict.items()]

 9
 BANANA FRIES 12
 POTATO CHIPS 30
 APPLE JUICE 10
 CANDY 5
 APPLE JUICE 10
 CANDY 5
 CANDY 5
 CANDY 5
 POTATO CHIPS 30


BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


[None, None, None, None]

### 5. Word Order

In [205]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())
words = {}

for i in range(n):
    word = input().lower()
    if word in words:
        words[word] += 1
    else:
        words[word] = 1

print(len(words))
print(' '.join(map(str, words.values())))


 4
 bcdef
 abcdefg
 bcde
 bcdef


3
2 1 1


### 6. collections.deque()

In [209]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from collections import deque

num = int(input())
d = deque()

for i in range(num):
    command_input = input().split()
    command = command_input[0]
    value = int(command_input[1]) if len(command_input) > 1 else None

    # Execute the command with or without value
    if value is not None:
        getattr(d, command)(value)
    else:
        getattr(d, command)()
print(*d)


 6
 append 1
 append 2
 append 3
 appendleft 4
 pop
 popleft


1 2


### 7. Company Logo

In [211]:
#!/bin/python3

import math
import os
import random
import re
import sys

from itertools import groupby
from collections import Counter



if __name__ == '__main__':
    s = input() 
    d = {}
    
    # Count occurrences of each character
    for i in s:
        d[i] = s.count(i)
    
    # Sort dictionary by key
    nd = dict(sorted(d.items()))
    
    # Print the character with the maximum count
    for j in range(3):
        if nd:  # Check if dictionary is not empty
            m = max(nd, key=nd.get)
            print("{} {}".format(m, nd[m]))
            nd.pop(m)
        else:
            break
  


 aabbbccde


b 3
a 2
c 2


### 8. Pilling Up!

In [213]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

T = int(input())
for _ in range(T):
    n = int(input())
    a  = list(map(int, input().split()))
    b = []
    while a:
        if a[0] >= a[-1]:
            b.append(a.pop(0))
        else:
            b.append(a.pop())
    if b == sorted(b, reverse = True):
        print("Yes")
    else:
        print("No")


 2
 6
 4 3 2 1 3 4


Yes


 3
 1 3 2


No


 ## **Data and Time** Total 2

### 1. Calendar Module

In [215]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import calendar
m, d, y = input().split()

y, m, d = int(y), int(m), int(d)
day_index = calendar.weekday(y, m, d)
days_of_week = list(calendar.day_name)

print(days_of_week[day_index].upper())


 08 05 2015


WEDNESDAY


### 2. Time Delta

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime as dt

# Complete the time_delta function below.
def time_delta(t1, t2):
    
    fmt = "%a %d %b %Y %H:%M:%S %z"
    deltaSeconds = abs((dt.strptime(t1, fmt)- dt.strptime(t2, fmt)).total_seconds())
    return str(int(deltaSeconds))
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()


 ## **Exceptions** Total 1

### 1. Exceptions

In [219]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

test_cases = int(input())
for i in range(0,test_cases):
    a, b = input().split()
    
    try:
        print(round(int(a)//int(b)))
        
    except Exception as e:
        print("Error Code:", e)


 3
 1 0


Error Code: integer division or modulo by zero


 2 $


Error Code: invalid literal for int() with base 10: '$'


 3 1


3


 ## **Built-ins** Total 3

### 1. Zipped!

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n, x = list(map(int, input().split()))
array = []

for _ in range(x):
    marks = list(map(float, input().split()))
    array.append(marks)

for i in range(n):
    total = 0
    for j in range(x):
        total += array[j][i]
    print(round(total / x, 1))


### 2. Athlete sort

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    nm = input().split()
    n = int(nm[0])
    m = int(nm[1])

    arr = []
    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())

    from operator import itemgetter

    def sort(k):
        def deco(f):
            def wrap(arr):
                arr.sort(key=itemgetter(k))
                return [f(athlete) for athlete in arr]
            return wrap
        return deco

    def person(athlete):
        return " ".join(map(str, athlete))

    decorated_person = sort(k)(person)
    print(*decorated_person(arr), sep='\n')



### 3. ginortS

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

string = input()
lower=""
upper=""
even=""
odd=""

for i in string:
    if i.isalpha():
        if i.islower():
            lower+=i
        else:
            upper+=i
    elif i.isnumeric():
        if int(i)%2==0:
            even+=i
        else:
            odd+=i
print("".join(sorted(lower)+sorted(upper)+sorted(odd)+sorted(even)))


 ## **Python Functionals** Total 1

### 1. Map and Lambda function

In [221]:
cube = lambda x:x**3

def fibonacci(n):
    list = []
    for i in range(n):
        if i == 0 or i == 1:
            list.append(i)
        else:
            x = list[i-1] + list[i - 2]
            list.append(x)
    return list


 ## **Regex and Parsing challenges** Total 17

### 1. Detect floating point number

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

T = int(input())

for k in range (T) :
    x = 1
    s = input()
    
    try :
        y = float (s)
        if s.count(".") == 0 :
            x = 0
            
    except :
        x = 0 
           
    print(bool(x))  


### 2. Re.spli()

In [ ]:
regex_pattern = r"\D"	# Do not delete 'r'.



### 3. Group() Groups() & groupdict()

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re
s = input()
rx = re.compile(r"([a-zA-Z0-9])(?=\1)")
print(rx.search(s)[0] if rx.search(s) else -1)


### 4. re.findall() & re. finfiter()

In [223]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

if __name__=="__main__":
    s = input()
    r = re.findall(r'(?<=[^aeiouAEIOU])[aeiouAEIOU]{2,}(?=[^aeiouAEIOU])',s)
    if not r:
        print(-1)
    else:
        for p in r:
            print(p)


 rabcdeefgyYhFjkIoomnpOeorteeeeet


ee
Ioo
Oeo
eeeee


### 5. Re.start() & re.end()

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

string = input()
k = input()

pattern = f"(?=({k}))"
matches = re.finditer(pattern, string)
indices = []

for match in matches:
    indices.append((match.start(), match.start() + len(k) - 1))


### 6. Regex substitution

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re
n = int(input())
s = "\n".join([input() for _ in range(n)])
patern = r'(?<=\s)&&(?=\s)|(?<=\s)\|\|(?=\s)'
print(re.sub(patern, lambda m: 'and' if m.group(0) == '&&' else 'or', s))


### 7. validating roman numerals

In [ ]:

regex_pattern = r"^(M){0,3}(CM)?(CD|D)?(C){0,3}(XC)?(XL|L)?(X){0,3}(IX)?(IV|V)?(I){0,3}$"



### 8. validating phone numerals

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

N = int(input())
for _ in range(N):
    phone_number = input().strip()
    if re.match(r'^[789]\d{9}$', phone_number):
        print("YES")
    else:
        print("NO")


### 9. validating and parsing email addressess

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

n = int(input())
email_pattern = re.compile(r"^<([a-zA-Z0-9%+][a-zA-Z0-9._%+-]*@[a-zA-Z]+\.[a-zA-Z]{1,3})>$")

for _ in range(n):
    name, email = input().split(maxsplit=1)
    email = email.strip()
    if email_pattern.match(email):
        print(f"{name} {email}")


### 10. Hex Color Code

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re
pattern = r'#[\da-fA-F]{3,6}'
res = []
for i in range(int(input())):
    lines = input()
    if len(lines)==0:
        continue
    if lines[0] != '#':
        m = re.findall(pattern, lines)
        [res.append(j) for j in m]
print(*res, sep='\n')


### 11. HTML Parser part 1

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start :", tag)
        if attrs:
            for each in attrs:
                print('-> '+' > '.join(list(map(str, each))))

    def handle_endtag(self, tag):
        print("End   :", tag)
        
    def handle_startendtag(self, tag, attrs):
        print("Empty :", tag)
        if attrs:
            for each in attrs:
                print('-> '+' > '.join(list(map(str, each))))

parser = MyHTMLParser()
for each in range(int(input())):
    parser.feed(input())


### 12. HTML Parser - part 2

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        if '\n' in data:
            print(">>> Multi-line Comment")
            print(data)
        else:
            print(">>> Single-line Comment")
            print(data)
            
    def handle_data(self, data):
        if '\n' not in data:
            print(">>> Data")
            print(data)
            

html = ""
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()
  
  
  

### 13. Detect HTML Tags, Atrr and Atrr values

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, att):
        print(tag)
        self.print_atributes(att)
    def print_atributes(self, att):
        for name, val in att:
            print(f'-> {name} > {val}')
        

parser = MyHTMLParser()
for _ in range(int(input())):
    parser.feed(input())


### 14. Validating UID

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

def validate_uid(uid):
    valid_alpha_count = bool(len(re.findall(r"[A-Z]", uid)) >= 2)
    valid_digit_count = bool(len(re.findall(r"\d", uid)) >= 3)
    alnum_only = bool(len(re.findall(r"[^\w]", uid)) == 0)
    no_repeat = not bool(re.search(r"(\w).*\1", uid))
    valid_char_count = bool(len(uid) == 10)
    return all([valid_alpha_count, valid_digit_count, alnum_only, no_repeat, valid_char_count])
    
testcase_count = int(input())
for _ in range(testcase_count):
    uid = input()
    if validate_uid(uid) == True:
        print("Valid")
    else:
        print("Invalid")


### 15. Validating Credit Card Numbers

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

def check_cb(cnum):
    if not bool(re.match(r"^[4,5,6]",cnum)):return "Invalid"
    if not bool(re.match(r"^\d{4}-\d{4}-\d{4}-\d{4}$|^\d{4}\d{4}\d{4}\d{4}$",cnum)):return "Invalid"
    if bool(re.search(r'(.)\1{3}',re.sub(r'\D', '', cnum))):return "Invalid"
    return "Valid"   
n = int(input())
print("\n".join([check_cb(input()) for _ in range(n)]))


### 16. Validating Postal Codes

In [ ]:
regex_integer_in_range = r"^[0-9]{6}$"
regex_alternating_repetitive_digit_pair = r"([0-9]{1})(?=[0-9]{1}\1)"    


### 17. Matrix Script

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys



first_multiple_input = input().rstrip().split()
n = int(first_multiple_input[0])
m = int(first_multiple_input[1])

regex = re.compile(r'(?<=\w)([\W]+)(?=\w)')
matrix = [None] * n * m

for x in range(n):
    matrix_item = [x for x in input()]
    for y in range(m):
        matrix[x+(n*y)] = matrix_item[y]
 
print(re.sub(regex, ' ', ''.join(matrix)))


 ## **XML** Total 2

### 1. XML - Find the score

In [227]:


def get_attr_number(node):
    attrs = len(node.attrib)
    if len(node) == 0:
        return attrs
    return attrs + sum(get_attr_number(child) for child in node)



### 2 XML - Find the Maximum

In [229]:


maxdepth = 0
def depth(elem, level= 0):
    global maxdepth
    [depth(e,level+1) for e in elem]
    maxdepth = max(maxdepth, level + 1)



 ## **Closures and Decorations** Total 2

### 1. Standardize Mobile Number Using Decorators

In [ ]:
from re import sub

def wrapper(f):
    r = r"^(?:\+?91|0)??(\d{5})(\d{5})$"
    s = r"+91 \1 \2"
    
    def fun(li):
        return f([sub(r, s, i) for i in li])
    return fun



### 2. Decorators 2 - Name Directory

In [ ]:


def person_lister(f):
    def inner(people):
        # complete the functiondef person_lister(f):
        return [f(p) for p in sorted(people,key = lambda x: int(x[-2]))] 
    return inner



 ## **Numpy** Total 15

### 1. Arrays

In [232]:


def arrays(arr):
    # complete this function
    # use numpy.array
    arr = arr[::-1]
    a = numpy.array(arr, float)
    return a
    
    

### 2. Shape and reshape

In [234]:
import numpy

s_input = list(map(int, input().split()))
arr = numpy.array(s_input)

print (numpy.reshape(arr, (3,3)))



 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3. Transpose and flattern

In [236]:
import numpy


r, c = map(int, input().split())

arr = [list(map(int, input().split())) for i in range(r)]

arr = numpy.array(arr, dtype=int)
print(numpy.transpose(arr))

print(arr.flatten())


 2 2
 1 2
 3 4


[[1 3]
 [2 4]]
[1 2 3 4]


### 4. Concatenate

In [ ]:
import numpy

n, m, p = map(int, input().split())
a1 = numpy.vstack([list(map(int, input().split())) for p in range(n)])
a2 = numpy.vstack([list(map(int, input().split())) for p in range(m)])
print(numpy.concatenate((a1, a2), axis=0))




### 5. Zeros and ones

In [238]:
import numpy 

M = list(map(int, input().split()))
print(numpy.zeros(M, dtype=int))
print(numpy.ones(M, dtype=int))


 3 3 3 


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### 6. Eye and identity

In [240]:
import numpy
numpy.set_printoptions(legacy='1.13')
N, M = map(int, input().split())

print (numpy.eye(N, M,))




 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 7. Array Mathematics

In [242]:
import numpy as np

m, n = map(int, input().split())

A = np.array([[x for x in input().split()] for i in range(m)], int)

B = np.array([[x for x in input().split()] for i in range(m)], int)

print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### 8. Floor, ceil and rint

In [ ]:
import numpy 
numpy.set_printoptions(legacy="1.13") 
A=list(map(float,input().split())) 
arr=numpy.array(A) 
print(numpy.floor(arr)) 
print(numpy.ceil(arr)) 
print(numpy.rint(arr))


### 9. Sun and prod

In [ ]:
import numpy as np

m,n = map(int, input().split())

arr = np.array([list(map(int, input().split())) for _ in range(m)])

sum= np.sum(arr, 0)

print(np.prod(sum))


### 10. Min and Max

In [ ]:
import numpy as np

x, y = map(int, input().split())

data = [list(map(int, input().split())) for _ in range(x)]

data = np.array(data)

result = np.min(data, axis = 1)

print(np.max(result))



### 11. Mean, var and std

In [ ]:
import numpy

import numpy as np

x, y = map(int, input().split())

matrix = [list(map(int, input().split())) for i in range(x)]

matrix = np.array(matrix)

print(np.mean(matrix, axis = 1))

print(np.var(matrix, axis = 0))

print(np.around(np.std(matrix, axis = None),11))


### 12. Dot and cross

In [ ]:
import numpy as np

n = int(input())

A =list(list(map(int, input().split())) for _ in range(n))

B =list(list(map(int, input().split())) for _ in range(n))

print(np.array(A)@(np.array(B)))



### 13. Inner and outer

In [244]:
import numpy as np

array_1 = np.array(input().split(), int)
array_2 = np.array(input().split(), int)

print(np.inner(array_1, array_2))
print(np.outer(array_1, array_2))



 0 1 
 2 3


3
[[0 0]
 [2 3]]


### 14. Polynomials

In [246]:
import numpy as np

p=list(map(float,input().split())) 
x=int(input()) 
arr=np.array(p) 
print(np.polyval(arr,x))


 1.1 2 3
 0


3.0


### 13. Linear Algebra

In [248]:
import numpy as np

n = int(input())
arr = []
for _ in range(n): 
    a = [list(map(float, input().split()))] 
    arr.extend(a)
print(round(np.linalg.det(np.array(arr)), 2))


 2
 1.1 1.1
 1.1 1.1


0.0
